
openapi: 3.0.0
info:
  title: 任務管理系統 API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: 取得任務列表
    post:
      summary: 建立新任務
  /tasks/{id}:
    put:
      summary: 更新任務
    delete:
      summary: 刪除任務
